name=EDCommon
version=0.1.0
author=Artem Kravchenko
maintainer=Artem Kravchenko
sentence=Some objects for home automations
paragraph=Like this project? Please star it on GitHub!
category=Other
url=https://github.com/lan143/ed-common
architectures=esp32
